### ISSUE TITLE
Add suppport to retain agent config between container redeployment with volumes

### ISSUE THREAD

**Issue by ghost** [mafen/playit-docker#1]
Changed the docker compose to just add a volume and was able to keep the config between deletion of the container and redeployment.

```
version: "3"

services:
  playit:
    container_name: playit
    image: ghcr.io/mafen/playit-docker:latest
    volumes:
      - ./config:/etc/playit
    restart: unless-stopped

**Comment by mafen** [comment]
Thanks for the suggestion, it is added in [03015c7](https://github.com/mafen/playit-docker/commit/03015c75e876a93fc1dbdaa6c5ba6e1e6b2df770)
