### ISSUE TITLE
application not executed after container start

### ISSUE THREAD

**Issue by JayKuswahey** [mafen/playit-docker#3]
Trying to set up a server for a school project of a family member, having never touched the game of playit.gg I have to say it seems pretty straightforward, so thanks for that! :) 

My docker run script

```
#!/usr/bin/env bash
DOCKERTAG='latest'

docker run -d\
	--name playitgg \
	--restart=unless-stopped \
	-e TZ="Europe/Amsterdam" \
  	-e "SET_CONTAINER_TIMEZONE=true" \
  	-e "CONTAINER_TIMEZONE=Europe/Amsterdam" \
  	-v /etc/localtime:/etc/localtime:ro \
  	-v /etc/timezone:/etc/timezone:ro \
	-v /path/to/data:/etc/playit \
	ghcr.io/mafen/playit-docker:${DOCKERTAG} \
```
However, the tunnel agent code never popped up. I checked some more search engines and came up with the following:

```
docker exec -ti playitgg bash
cd /opt/playit
 ./playit --secret_path /etc/playit/playit.toml
``` 
this allowed me to link the programme to my account and I was able to create a couple tunnels. Awesome!

After the container restart however, the agent did not start.

In the Dockerfile it states

```
CMD playit
```
but that might have to be changed into `/opt/playit/playit` or add `/opt/playit` into the container user `PATH` variable?

Thanks, and sorry if I have overlooked something!? Keep up the good work!

And I think, not sure, that the container needs to run in the `host` network, else the default tunnels to `127.0.0.1` won't work?

**Comment by mafen** [comment]
Can you test if it works with https://github.com/mafen/playit-docker/commit/8fb2c80c13b375726f5ac390ccc61a62e1f73b73

Ref host network is not needed to reach other services or servers, you can route it to any ip on your network. A docker network might needed if you want to reach other docker containers using the docker networks.

**Comment by mafen** [comment]
> Trying to set up a server for a school project of a family member, having never touched the game of playit.gg I have to say it seems pretty straightforward, so thanks for that! :)
> 
> My docker run script
> 
> ```
> #!/usr/bin/env bash
> DOCKERTAG='latest'
> 
> docker run -d\
> 	--name playitgg \
> 	--restart=unless-stopped \
> 	-e TZ="Europe/Amsterdam" \
>   	-e "SET_CONTAINER_TIMEZONE=true" \
>   	-e "CONTAINER_TIMEZONE=Europe/Amsterdam" \
>   	-v /etc/localtime:/etc/localtime:ro \
>   	-v /etc/timezone:/etc/timezone:ro \
> 	-v /path/to/data:/etc/playit \
> 	ghcr.io/mafen/playit-docker:${DOCKERTAG} \
> ```
> 
> However, the tunnel agent code never popped up. I checked some more search engines and came up with the following:
> 
> ```
> docker exec -ti playitgg bash
> cd /opt/playit
>  ./playit --secret_path /etc/playit/playit.toml
> ```
> 
> this allowed me to link the programme to my account and I was able to create a couple tunnels. Awesome!
> 
> After the container restart however, the agent did not start.
> 
> In the Dockerfile it states
> 
> ```
> CMD playit
> ```
> 
> but that might have to be changed into `/opt/playit/playit` or add `/opt/playit` into the container user `PATH` variable?
> 
> Thanks, and sorry if I have overlooked something!? Keep up the good work!
> 
> And I think, not sure, that the container needs to run in the `host` network, else the default tunnels to `127.0.0.1` won't work?

I have tested with my own server and it works now

**Comment by JayKuswahey** [comment]
> Can you test if it works with [8fb2c80](https://github.com/mafen/playit-docker/commit/8fb2c80c13b375726f5ac390ccc61a62e1f73b73)
> 
> Ref host network is not needed to reach other services or servers, you can route it to any ip on your network. A docker network might needed if you want to reach other docker containers using the docker networks.

Hi, sorry for not replying, different timezone perhaps :) 

Agreed on the host network. I wasn't thinking right, except for the fact that the playit default tunnel points to `127.0.0.1` which does require that I think, plus my minecraft "bedrock" server was failing. After switching to "java" it did work, and I could indeed just point the tunnel to the actual IP address of the machine and have the game also listen on `0.0.0.0` instead of `127.0.0.1`. 👍🏼 

Regardless, that was not an image issue but a network issue. 💯 

Thanks for the swift solution, awesome!
